### ISSUE TITLE
Submit Polish youtube creator

### ISSUE THREAD

**Issue by kannthu** [ZetaTwo/security-creators#18]
Hi, I have Polish youtube channel about security. I talk about bug bounty and recent bugs found in software. 
Do I qualify to I be added to the creators list?

My youtube channel: https://www.youtube.com/channel/UCT2_r44LibWOJcDQJgmYyxw/

**Comment by ZetaTwo** [comment]
Hi!

Yes I think there is room for this but I think I will create a separate section for non-English content where I can list you.
I will need to make some changes to the layout before publishing this but in the meanwhile, please submit a PR similar to this one: https://github.com/ZetaTwo/security-creators/pull/16 but also add "language": "pl" as an attribute in the JSON.

Does that sound good?

**Comment by ZetaTwo** [comment]
Closing this from inactivity, feel free to do the PR as stated above.
